version: 2.1
orbs:
  # aws-ecr: circleci/aws-ecr@8.0.0
  aws-ecr: circleci/aws-ecr@6.15.1
  aws-ecs: circleci/aws-ecs@2.0.0
  aws-cli: circleci/aws-cli@2.1.0

jobs:
  build:
    docker:
      - image: 'cimg/python:3.9.1'
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_REPOSITORY_URL
          # aws-access-key-id: AWS_ACCESS_KEY_ID
          # aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          # dockerfile: Dockerfile
          # path: .
          region: AWS_DEFAULT_REGION
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"
      # - checkout
      # - setup_remote_docker:
      #     docker_layer_caching: true
      # - aws-ecr/ecr-login:
      #     registry-id: AWS_ECR_REPOSITORY_REGISTRY_ID
      #     region: "${AWS_DEFAULT_REGION}"
      # - aws-ecr/build-image:
      #     registry-id: AWS_ECR_REPOSITORY_URL
      #     repo: "${AWS_RESOURCE_NAME_PREFIX}"
      #     region: "${AWS_DEFAULT_REGION}"
      #     tag: "${CIRCLE_SHA1}"
      #     dockerfile: Dockerfile
      #     path: .
      #     push-image: true
  deploy:
    machine: true 
    steps:
      - aws-ecs/update-service:
          container-env-var-updates: container=${AWS_RESOURCE_NAME_PREFIX}-service,name="TEXT",value="${TEXT}"
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          cluster-name: "${AWS_ECS_CLUSTER_NAME_PREFIX}-cluster"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,image-and-tag=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:${CIRCLE_SHA1}"
          verify-revision-is-deployed: true
      - run:
          name: Test deployment (Please manually tear down AWS resources after use, if desired)
          command: |
            TARGET_GROUP_ARN=$(aws ecs describe-services --cluster ${AWS_ECS_CLUSTER_NAME_PREFIX}-cluster --services ${AWS_RESOURCE_NAME_PREFIX}-service | jq -r '.services[0].loadBalancers[0].targetGroupArn')
            ELB_ARN=$(aws elbv2 describe-target-groups --target-group-arns $TARGET_GROUP_ARN | jq -r '.TargetGroups[0].LoadBalancerArns[0]')
            ELB_DNS_NAME=$(aws elbv2 describe-load-balancers --load-balancer-arns $ELB_ARN | jq -r '.LoadBalancers[0].DNSName')
            curl -s -o --retry 10 /dev/null -w '%{http_code}' http://$ELB_DNS_NAME | grep 200

      # - aws-ecs/deploy-service-update:
      #     requires:
      #       - aws-ecr/build-and-push-image
      #     aws-region: ${AWS_DEFAULT_REGION}
      #     container-env-var-updates: container=${AWS_RESOURCE_NAME_PREFIX}-service,name="TEXT",value="${TEXT}"
      #     family: "${AWS_RESOURCE_NAME_PREFIX}-service"
      #     cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
      #     container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,image-and-tag=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_RESOURCE_NAME_PREFIX}:${CIRCLE_SHA1}"
      #     verify-revision-is-deployed: true
      #     post-steps:
      #       - run:
      #           name: Test the deployment
      #           command: |
      #             TARGET_GROUP_ARN=$(aws ecs describe-services --cluster ${AWS_RESOURCE_NAME_PREFIX}-cluster --services ${AWS_RESOURCE_NAME_PREFIX}-service | jq -r '.services[0].loadBalancers[0].targetGroupArn')
      #             ELB_ARN=$(aws elbv2 describe-target-groups --target-group-arns $TARGET_GROUP_ARN | jq -r '.TargetGroups[0].LoadBalancerArns[0]')
      #             ELB_DNS_NAME=$(aws elbv2 describe-load-balancers --load-balancer-arns $ELB_ARN | jq -r '.LoadBalancers[0].DNSName')
      #             curl -s -o --retry 10 /dev/null -w '%{http_code}' http://$ELB_DNS_NAME | grep 200
workflows:
  build-and-deploy:
    jobs:
      - build:
          name: 'build-dev'
          context:
            - aws-payfaction-dev
            - aws-resources-payfaction-dev
            - accounts-dev
          filters:
            branches:
              only:
                - develop
      - deploy:
          name: 'deploy-dev'
          requires:
            - build-dev
          context:
            - aws-payfaction-dev
            - aws-resources-payfaction-dev
            - accounts-dev
          filters:
            branches:
              only:
                - develop
      - build:
          name: 'build-prod'
          context:
            # - aws-payfaction-prod
            # - accounts-prod
            - aws-payfaction-dev
            - aws-resources-payfaction-dev
            - accounts-dev
          filters:
            branches:
              only:
                - master
      - deploy:
          name: 'deploy-prod'
          requires:
            - build-prod
          context:
            # - aws-payfaction-prod
            # - accounts-prod
            - aws-payfaction-dev
            - aws-resources-payfaction-dev
            - accounts-dev
          filters:
            branches:
              only:
                - master
